version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint

jobs:
  lint:
    docker:
      - image: devsnest/python:3.7.4-alpine3.12
    steps:
      - checkout
      - run:
          name: Run Black
          command: black --check .
      - run:
          name: Run isort
          command: isort --check-only .
